### ISSUE TITLE
APP_NAME, API_NAME views (performance)

### ISSUE THREAD

**Issue by usfalami** [oneteme/traceapi-app#5]
1. request count,  
2. elapsedtime (avg, max) / version ?
3. fails (most frequent errors ) / version ?
4. Dependents (APIs)
5. Dependencies (APIs)
6. Clients ??

**Comment by antonin77** [comment]
=> Dependancies : Quels sont les microservice qui utilise l'api en question ? (Graphique avec le % d'utilisation par microservice par exemple)
